name: Test-Lint ExpenseMe Application

on:
  push

defaults:
  run:
    shell: bash
    working-directory: app

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install nvm and node
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        nvm install v12.18.3
        nvm use
    - name: Install yarn
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt update && sudo apt install --no-install-recommends yarn
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test
